# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - when:
          condition:
            equal: [ dist, << pipeline.git.branch >> ]
          steps:
            - run:
                command: npm ci
                name: Run clean install
            - run:
                command: npm run test
                name: Run tests
            - run:
                command: npm run build
                name: Build app

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
